// <auto-generated />
using System;
using Gestao.Residuos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Gestao.Residuos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestao.Residuos.Models.AgendamentoColetaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacidadeAtualRecipiente")
                        .HasColumnType("NUMBER(10,2)");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("DATE");

                    b.Property<int>("MoradorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("MoradorId");

                    b.ToTable("AGENDAMENTOS_COLETAS", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.AuthModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("AuthUser", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.CaminhaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapacidadeMaxima")
                        .HasColumnType("NUMBER(10,2)");

                    b.Property<string>("LocalizacaoAtual")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)");

                    b.HasKey("Id");

                    b.ToTable("CAMINHOES", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.MoradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(15)");

                    b.HasKey("Id");

                    b.ToTable("MORADORES", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.ResiduoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstrucoesDescarte")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id");

                    b.ToTable("RESIDUOS", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.RotaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("DATE");

                    b.Property<string>("Paradas")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CaminhaoId");

                    b.ToTable("ROTAS", (string)null);
                });

            modelBuilder.Entity("Gestao.Residuos.Models.AgendamentoColetaModel", b =>
                {
                    b.HasOne("Gestao.Residuos.Models.MoradorModel", "Morador")
                        .WithMany()
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("Gestao.Residuos.Models.RotaModel", b =>
                {
                    b.HasOne("Gestao.Residuos.Models.CaminhaoModel", "Caminhao")
                        .WithMany()
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");
                });
#pragma warning restore 612, 618
        }
    }
}
